'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AccountSettings

    '''<summary>
    '''tbFirstName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbFirstName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbLastName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbLastName As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbEmail As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbPassword control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPassword As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbStreetAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbStreetAddress As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbCity As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbState As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''tbPostalCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tbPostalCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnCreateCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCreateCustomer As Global.System.Web.UI.WebControls.Button
End Class
