'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class APIClient

    '''<summary>
    '''LoginID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LoginID As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''TransactionKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TransactionKey As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CardHolder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardHolder As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''CardNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CardNumber As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''ExpirationDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ExpirationDate As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''SecurityCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SecurityCode As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Amount As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''btnSendPayment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSendPayment As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ResponseLbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ResponseLbl As Global.System.Web.UI.WebControls.Label
End Class
