'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CreditCardInfo
    Public Property CardId As Integer
    Public Property CardNumber As String
    Public Property CardHolder As String
    Public Property ExpirationDate As String
    Public Property SecurityCode As String
    Public Property CreditFund As Decimal
    Public Property OnHold As Integer
    Public Property UserID As Integer

End Class
